### ISSUE TITLE
Not 64bit compatible

### ISSUE THREAD

**Issue by wonea** [markbeaton/TidyManaged#3]
After moving to x64, tidylib now throws an exception when Document object is created.  "BadImageFormatException occured - An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"

This seems like a 64bit problem as it was working fine beforehand.  More talk is available here;
http://stackoverflow.com/questions/4002346/c-version-of-html-tidy

**Comment by markbeaton** [comment]
I've just tried my 64-bit build of libtidy.dll under 64-bit Windows 7, and as long as the TidyManaged wrapper code is built using "Any CPU" and your referencing project is also "Any CPU", things work fine. If running under ASP.NET, you'll need to make sure your app pool is running in 64-bit mode as well ("Enable 32-bit applications" should be false).

**Comment by rainman74** [comment]
@markbeaton could you please share your 64-bit build of libtidy.dll?
